### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by ix1ali** [fkk-cz/noire-public#1014]
I noticed that the food at the grocery store fills you up just as much as the restaurants food does

Which isn't a good thing, By reducing the filling from every food in the grocery store and increasing it in restaurants food players will choose to go to the restaurants more, Then they would have a a real benefit/use.

Food in grocery stores should only fill you up a tiny tiny bit, And edit the hospitals check ins so that it doesn't fill your hunger by 50%, Make it 10%.

**Comment by tythetanman** [comment]
By doing so, it would also increase traffic to each restaurant and potential incoming restaurants. 

Then increasing more interactions.

**Comment by tythetanman** [comment]
The thing is, it would have to be lowered even more. Those only do about 10% per item in the store, I thought.

**Comment by noyeahsure** [comment]
how about we give player owned food restaurants some buffs. ie: food and water drains less when eating at a restaurant, instead of always just trying to nerf 😭

**Comment by tythetanman** [comment]
Not so much about trying to force people to go to restaurants it’s to increase interaction. It’s role-playing, not just going to an empty building where there actually should be someone working the counter. 

Unless there’s a way to have someone working these convenient stores that would be an alternative.

**Comment by noyeahsure** [comment]
if thats the case lets get real people working at insurance, clothing stores, ls customs,
not everything can be done manually nor should it have to. burgershot has been open for so long, and no one has brought up gas station food before. 
like i said instead of forcing people to go to restaurants (which what yall are suggesting would) just give player pwned food businesses a buff. and if people wanna go they will go.

**Comment by tythetanman** [comment]
No one brought that up before because it was just one restaurant. The city is growing you add things.

Like you said you just named one restaurant, there are more than one now, and there are more to come. 

It’s not like food is being taken away from gas stations, and it’s just a suggestion and you have a alternative suggestion that could be better. 
let’s see if and if anything is even changed or decided
