### ISSUE TITLE
BOUNTY HUNTER (WHITELIST JOB) 

### ISSUE THREAD

**Issue by CjSSB13** [fkk-cz/noire-public#1018]
So i was thinking of a way u can make my business for me, i would work with court,lspd,hp and start a bounty hunting business. So i would get a group of people i would hire we would all be in our matching bounty hunter outfits and we would have a list of people that have warrants and we would have there info to get in contact setup a (fake meeting) or stalk outside there house. I teally think this would help with more rp in city and give people other things if they cant become pd or hp and still wanna help out. Please think about this it would be a great idea

**Comment by Jakebeastt** [comment]
First, I just want to say I think its a good idea and has a creative outcomes to it. But Thats kinda what we have cops for ? I understand we have bounty hunters in real life its just like,  we don't really need "bounty hunters" in a server like this because there's lot of cops on at some points.  and with the police and the court  being the main source of telling you guys who needs to be arrested. yeah it being for Rp but its just like being a police officer.

**Comment by okxeon** [comment]
A new sheriffs department is being created to do just that. Part of their job would be to try and locate individuals who have warrants and arrest them.
