### ISSUE TITLE
Purchasable and functional backbacks

### ISSUE THREAD

**Issue by CasperBoiRL** [fkk-cz/noire-public#1030]
Make purchasable and functional backpacks that allow you to hold 500 storage instead of the usual 250.

**Comment by CasperBoiRL** [comment]
Lose when you die

**Comment by Fallinglol** [comment]
500 storage is quite a lot don't you think? Most cars don't even have that trunk space.

**Comment by CasperBoiRL** [comment]
i just said that bc it’s double. maybe 400 would be better

**Comment by fkk-cz** [comment]
250 units of storage is sufficient for a player's personal inventory. You might as well just ask directly for an inventory capacity increase, instead of trying to mask it behind some backpack item.

To help with confusion and improve the user experience, the weight should probably be displayed, similar to the trunk.

**Comment by CasperBoiRL** [comment]
the reason i asked, is because it will help most jobs, like fishing, hunting, and mining.
