### ISSUE TITLE
Easier Way To Lower Vehicle Windows

### ISSUE THREAD

**Issue by Chitowndevil21** [fkk-cz/noire-public#1032]
So this is gonna seem silly but is there an easier way to roll ur windows down??  The reason I am asking is because I have cars where I have chosen to have the roof off & they look better to me with the windows down.There used to b the F5 menu but they took that away, then I would just hop in the driver & passenger seat & give the finger which worked but now u have to b moving to give the finger...don't know y...so now I can't do the passenger window unless I have someone riding with me.  Is it possible to bring the F5 menu back??

**Comment by CasperBoiRL** [comment]
Absolutely need this

**Comment by fkk-cz** [comment]
The menu you're referring to was removed because it was also used for checking/giving ID, which was moved to the contextual system. I'm trying to think of an intuitive way for this, aiming while unarmed doesn't seem so given how many people ask "how do I roll down my window????" and struggle doing so.

Police should probably have some contextual option at the driver/passenger doors which temporarily gives the driver a notification prompt with keybinds to control all the vehicle's windows, doors, and lights.

In the meantime I'll re allow the unarmed drive-by thing as a temporary solution.
