### ISSUE TITLE
Advanced City Fishing/illegal Fishing-Boat rentals

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#1085]
This is going to be for advanced fishing in the city. It is a ESX script as well.  It would bring a bit of a twist to the fishing job. 

That includes illegal fish, and would also give the sheriffs department something else to manage on the lines of fish and game department within the sheriffs department.  

That way the sheriffs department could monitor the illegal sell and trade of exotic fish and potentially also monitor the hunting area, making it a full fish and game section of the sheriffs department, adding for them to do more in the city to have more to do with fishing, so fishing has more levels to it.

https://github.com/Kuzkay/esx_AdvancedFishing

[[Release] Advanced fishing - FiveM Resource Development & Modding / Releases - Cfx.re Community](https://forum.cfx.re/t/release-advanced-fishing/277267)

**Comment by PsychoticCore** [comment]
This would be dope for the city and popularize fishing give more things for people to do

**Comment by tythetanman** [comment]
Push more traffic out of mining… cough cough or help when mining leaves 😂

**Comment by CharlottePett** [comment]
Yes this is brilliant it would stop the 60+ minners and give other people a simple legal too do!!!

**Comment by PsychoticCore** [comment]
> Push more traffic out of mining… cough cough or help when mining leaves 😂

Could replace mining I feel like if properly done, be able to buy boats and the bigger the boat the more fish you can put in the "storage" also have it cost more obviously so have something you have to invest in to make more money and have basic boat rentals from the city itself so new players can also have a shot at this

**Comment by tythetanman** [comment]
It comes with boat rental section of the script.

**Comment by fkk-cz** [comment]
Can people please stop suggesting generic legals and providing links to somewhat commoditized public (or even paid, for that matter) releases for things that have been purposely shelved for a while with good reason?

**Yes, I am aware that the legals need to be reworked and am in the process of doing so.** *Please stop suggesting things such as this, it only makes the issue worse and more frustrating as I have to spend time responding.* Fishing has always been broken, and I can't see any design or implementation that doesn't have the same issues that mining has.

In general, it's hard to add new legals or replace/rework existing ones for the following reasons:
- Any new suggestions are too similar to existing jobs
- The job is inherently flawed in such a way where players can easily grind with little to no effort with a disproportional reward or payout, e.g. mining
- Job requires vehicle spawning which leads to entity buildup issues at spawn points
- Job has a limited number of static locations and players end up seeing each other at job sites, often causing issues with RDM/other dumb shit we see in reports. Good job design will limit the amount of location predictability and help reduce these issues often caused by newer players.
- Not enough availability/does not scale well. Certain jobs have limited resources and demand greatly exceeds supply. Expanding the number of jobs/spots/whatever is not a good solution at all.
- Imbalance with other jobs. As seen with mining and landscaping, players will often do whatever job pays the most, regardless of other considerations. This leads to overcrowding, among other issues.

For public releases, these tend to be either unmaintained (if free), or obfuscated/encrypted/completely broken if paid. These release authors tend to not know what they're doing and the latter makes it even worse from my perspective. Additionally, a lot of these resources tend to be incredibly unsecured and easily exploitable with cheats.

I'm working on a few good ideas for some new legals to replace existing ones, amongst other things. These will be released sooner than expected. I want people to understand that it's incredibly difficult to come up with creative and unique ideas that will actually work instead of just sounding good on paper.

**Comment by tythetanman** [comment]
Thank you for the reply and the new things to come.
