### ISSUE TITLE
Would Like to Open a business  

### ISSUE THREAD

**Issue by ImDead48** [fkk-cz/noire-public#1181]
I have a few ideas and would like to see if your interested in hearing any of them, and be willing to let me own a business. Discord is Im Dead#0048

**Comment by okxeon** [comment]
List the ideas in here.

**Comment by ImDead48** [comment]
1. My first idea would be for be to take over Bean Machine since I never see it open.

2. A arcade where you can play games and order drinks/food

3. A smoothie shop where I sell drinks mostly smoothies, and food.

I do have interiors for 2 and 3

**Comment by BradleyYates** [comment]
I've had a new business idea i think would be great to have in the city, so I've been thinking about a hotel, I don't have a specific location in mind but I've looked around and seen a few spots that would be good which don't have houses on them, so my idea is having a hotel which has many rooms that can be rented out weekly, these rooms will have a storage capacity of around 4k, the keys to the room cannot be shared but other people can be invited into the room, the rooms will include: a wardrobe where people can change their clothes, a safe with a capacity of 4k, possibly a fridge where food and drinks can be placed separately to create less junk in the safe, an option to call for room service which will add food/ drink to their fridge (will be paid for) - i could think of many more ideas but not all of these would be needed, the hotel could include a main desk where people will pay for their rooms (5k per week), they will also have the option to cancel their subscription and will have a 3 day leave to remove everything from their safe, anything they do not remove will be put in a lost and found which only staff will have access to with logs to see whos item is whos. the hotel could also include a bar where people can hang out and buy drinks, this could be a job for one or two people, there could also be hotel workers who stay on the premises to help anyone who is in need of help, there could also be security at certain times to make sure no conflict happens on the premises, if anybody is to cause conflict or commits serious crime they will get a partial refund depending on how long they have left of their stay. i do understand this may not be easy to do and will have to be thought about, i personally think its a great idea because some people cannot afford to pay to buy a house or are newer to the city and not sure if its in their best intrest, tho this could lean people towards the purchase of supporter once they find out how usefull safes can be, this will also open up new opportunities for whitelisted jobs that can be offered to people, Thanks for reading- Bradley

**Comment by ImDead48** [comment]
I would like to keep this topic up to date pls. I enjoy the city and would like to hopefully see this

**Comment by fkk-cz** [comment]
Feature requests such as player owned businesses has moved to the discussions section on Discord. GitHub issues will be used for reporting bugs only.
