### ISSUE TITLE
[BUG]: Taxi employees not able to buy vehicles 

### ISSUE THREAD

**Issue by TheBottomFragger** [fkk-cz/noire-public#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have had problems today and yesterday where we can’t buy vehicles. Or well, it’s more the fact that it’s taking the dollar, but nothing is actually being bought. 

This is causing issues because people that wanna  clock in that doesn’t already have the vehicle can’t clock in, unless we spawn in a vehicle we already have. 

It got nothing to do with the ranks as not even the executives can buy a new vehicle. 

We also have another issue that also started 2 days ago. When someone tries to pull out a taxi, it starts smoking instantly. It only happens with some of the vehicles. 

If possible, can we get the taxi meter removed as it’s only causing issues every time someone presses F3, to the point where we got to relog sometimes. 

### Expected Behavior

This worked 2 days ago where even recruits were able to buy and spawn a vehicle, but it’s not working anymore and causing issues for new recruits. 

### Steps To Reproduce

If you try to buy a new taxi, you’ll see that you won’t be getting that vehicle in the garage. 

### Anything else?

A clip can be provided if it’s needed.

**Comment by cxerq** [comment]
Don't forget about the Meter being bugging and making you relong if sometimes if you try and use it!

**Comment by fkk-cz** [comment]
This bug was inadvertently introduced in https://github.com/fkk-cz/noire/commit/65a78188390dd125acfd3cf4357ccc0677e8d44b (fix(server): correct vehicle type in database - fkk-cz) when I decided to start tracking the correct vehicle type for newly purchased vehicles, e.g. `automobile`, `bike`, `trailer`, etc. instead of just `car` -- a type that does not natively exist.

Turns out this caused an issue with how job vehicles are fetched, which requires the `car` type. Considering how job vehicle types can include both cars and helis (and the fact only one type can be fetched at a time), this change will have to be reverted.

> When someone tries to pull out a taxi, it starts smoking instantly. It only happens with some of the vehicles.

I didn't have any issues spawning vehicles in the garage. Might be a model issue?

**Comment by TheBottomFragger** [comment]
> This bug was inadvertently introduced in https://github.com/fkk-cz/noire/commit/65a78188390dd125acfd3cf4357ccc0677e8d44b (fix(server): correct vehicle type in database - fkk-cz) when I decided to start tracking the correct vehicle type for newly purchased vehicles, e.g. `automobile`, `bike`, `trailer`, etc. instead of just `car` -- a type that does not natively exist.
> 
> Turns out this caused an issue with how job vehicles are fetched, which requires the `car` type. Considering how job vehicle types can include both cars and helis (and the fact only one type can be fetched at a time), this change will have to be reverted.
> 
> > When someone tries to pull out a taxi, it starts smoking instantly. It only happens with some of the vehicles.
> 
> I didn't have any issues spawning vehicles in the garage. Might be a model issue?

For the smoking issue, I’m gonna be honest, I haven’t had that problem yet, but I know that Stevie had that issue, and some of the other drivers and recruits!
