### ISSUE TITLE
[BUG]: twitter auto suspension AGAIN

### ISSUE THREAD

**Issue by noyeahsure** [fkk-cz/noire-public#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

like i said, tweeting certain people names and not even ooc shit will get you banned on twitter, here is a clip of NOTHING ELSE OOC being tweeted but me tweeting pooch gets me suspended.. maybe try it yourself... as like i said even other people who hadnt tweeted that day tweeted the word and got suspended.. 

### Expected Behavior

not to get suspended for non ooc shit. 

### Steps To Reproduce

1. again. tweet the word pooch
2. get suspended. 

### Anything else?

https://streamable.com/yfin0c

**Comment by fkk-cz** [comment]
Twitter moderation was previously done by checking whether an individual string exists in a message, irrespective of word boundaries. The word above improperly caused a suspension because of the word `ooc`. This has been partially fixed but can be improved by using individual regex patterns for each individual entry on the badwords list.

**Comment by fkk-cz** [comment]
Replaced the old badWords list in `config.json` with a pattern table. New words will be added as reports come in to avoid this issue going forward.
