### ISSUE TITLE
[BUG]: <Dying spawning in open interior houses>

### ISSUE THREAD

**Issue by somedudenamedrush** [fkk-cz/noire-public#1293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i die spawning in my open interior house 

https://medal.tv/games/gta-v/clips/Upom2BpTMEVXw/d1337cT1BpR5?invite=cr-MSxNWnQsNjE1MzMwNyw

### Expected Behavior

i expect not to die

### Steps To Reproduce

fly out in open interior house
fly back in 
die

### Anything else?

some type of fix would be nice

**Comment by fkk-cz** [comment]
Made some adjustments to the first spawn death state handler. This issue usually coexists with the duplicate death timers, or people falling through the map due to the world not loading in time. Not sure how to fix the latter, as there's already collision checks in place to ensure the player is frozen and cannot move until the collision has loaded around the player.

The steps you provided also don't repro consistently -- some people seem to have this issue more than others.
