### ISSUE TITLE
[BUG]: cannot pull trailer out of garage

### ISSUE THREAD

**Issue by slimesays** [fkk-cz/noire-public#1324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when attempting to get trailer out of garage prompt “invalid vehicle type” pops up

### Expected Behavior

trailer should be taken out of garage and be available for use.

### Steps To Reproduce

go to garage
choose trailer

### Anything else?

happens in public and private garage before and after relogging and before and after going to insurance

**Comment by fkk-cz** [comment]
This is caused by the complete removal of all client-side/RPC calls for CreateVehicle. Unfortunately there doesn't seem to be any way to determine whether a vehicle model is a `trailer` type, hence the invalid vehicle type error. I'll whitelist the small trailer model for now, until a better solution can be found as I don't anticipate any new trailers being added.
