### ISSUE TITLE
[BUG]: INPUT_JUMP disabled for cleaning

### ISSUE THREAD

**Issue by Souji3250** [fkk-cz/noire-public#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Jumping is disabled for for cleaning(sunset bleach) job and unable to get pieces of trash that spawn on the bed in houses and apartments making player unable to complete jobs which results in player unable to leave unless the player disconnects.

### Expected Behavior

Player should be able to jump to be able to get pieces of trash that spawn on top of surfaces that cannot be reached unless said player jumps. 

### Steps To Reproduce

In this environment this action is easily reproducible and noticeable due to pieces of trash within the "house" environment will always spawn on top of the bed in the master bedroom. Due to player not being able to jump the player cannot complete the task which results in the player being stuck within the work zone unless they disconnect. 

### Anything else?

![image](https://github.com/fkk-cz/noire-public/assets/135337449/32d64e5b-ec2a-426f-8183-4bb23a10ef9e)

**Comment by fkk-cz** [comment]
This change was introduced because players kept jumping in the 'Low End Apartment' interior near the staircase which would lead to them falling into another nearby interior and complaining/placing assists asking for us to get them out. Didn't realize the range was *that* limited to the point where you can't pickup items from a short distance as shown in your screenshot. Reverted in https://github.com/fkk-cz/noire/commit/296fa0543ba47b3ec09f63fcae054a8e9b13cee9 for next reset.
