### ISSUE TITLE
[BUG]: player ped disappearing in house

### ISSUE THREAD

**Issue by cheezball07** [fkk-cz/noire-public#1336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the house interior with 3 floors make your player ped disappear in most areas.

### Expected Behavior

the player ped doesnt disappear

### Steps To Reproduce

1. go into a house interior with 3 floors
2. walk around

### Anything else?

a change of interior

**Comment by Mynameisnotlenny** [comment]
This isn't an issue with the specific interior shell, it is an issue with where your house is located there is a collision causing you to appear invisible. You either need a different/smaller shell or a house relocation. I can confirm the 3 story shell works because I have it and have had no issues. Open a ticket and explain the situation should get resolved from there.

**Comment by cheezball07** [comment]
thanks, ive been having this issue for a good while
