### ISSUE TITLE
I am requesting a chat with FKK 

### ISSUE THREAD

**Issue by natenectar** [fkk-cz/noire-public#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

just really down in the dumps tonight from the news I have received, telling me I can't even obtain an interview for Highway because of my last name in city, 5 recommendation's, I turned down the med director job at amr, because I thought I could have a chance of at least getting an interview with my background, and that many recommendations, the higher ups at the department was for at least giving me an interview, but apparently they was told no because of my last name, there's other cops in city that is involved or has been in my family, and there hasn't been any issues with them. and my reputation through the community should be known that I would never use my title in city to anyones advantage, if it takes me leaving, and cutting ties I am willing to do that, but truthfully it should not have to come to that, if i was just given a chance, to prove whatever you guys is thinking is false, I promise you would not ever have one single issue come from me. I still have people in the department sticking up for me, and calling this unfair, and i should still have a chance.  

### Expected Behavior

Ever since i joined the city, I've always wanted to become a cop, mostly highway, im 2000 hours in city, have never joined a gang, never slid, joined amr when i was 86 hours in city, and now i am pushing 2000 hours, I have never had any kind of ban, warning or been in any type of trouble for you guys to label me as a person not eligible to have this type of opportunity. I just feel singled out, for something out of my control, labeled for problems ive never created or been apart of, and judged for something thats simply not there. I understand the problem at hand, if you think I was an officer, thinking that I would be in discord sharing my screen, to give people an advantage, to that I would like to say, let me prove you wrong, and to just give me a chance, myself in city has never created 1 single problem for anyone to pass this type of judgment onto me, there's other big families in cities that have cops within their family, this should be no different than that. and to the cops thats came from our family, or friends of the family, there has never been 1 single problem of that nature, why would I want to ruin this type of opportunity, of what ive been trying to build a good rep in city for myself to get, and ruin it over something as stupid as that, after all this time, I just feel extremely let down and bummed out that this is what I get, for all the time ive put in making a good name for myself  

### Steps To Reproduce

If I need to leave the family, cut ties and move on for me to have an opportunity i will do so 
i am at least worth an interview, just listen to what i have to say, and maybe I can change your mind, give me a chance, and the very first thing you guys think is fishy, just let me go, no warning, blacklisted w/e has to be done, you can blacklist me from every single WL in the city if you want, I trust in myself enough to know, if given the chance you guys will never have one single issue out of me, just because of what my last name is 

### Anything else?

Just that this will honestly impact my discussion rather or not I should stay in this city, it hurts to think about leaving something i care very much for, i've made long term friendships, met great people from all around the world from something your team has built, but I just feel as if I am being judged for something imaginary, at least give me a shot to prove myself, and to show you that whoever is labeling me is wrong.

**Comment by Chunky30** [comment]
Goodnight Mr natenectar, 

First of all I would like to express my lost for words of this GitHub post for multiple reason. First of all the public GitHub repo is for vehicle, bug or game suggestions reasons, to which this appears to be none of the previous. I find it very immature for this sort of public statement towards the San Andreas Highway Patrol (SAHP) coming from an individual with the knowledge of running an agency (AMR).

First of all, the Whitelist has limited spots and I would be flabbergasted if you think that you are the only interested person, there are many individual that are looked over, and centering yourself with this issue is not appropriate. Recommendations are a good step to start, but are to no extent a guarantee. The department is not going to see itself forced to hire someone because people want them in the department, if anything, stuff like this will hinder this significantly.

To cut this short, in conclusion, staff does not run SAHP nor other Law Enforcement agencies. Decisions are made by the supervisors. Second of all again, like mentioned, this GitHub section is not for personal issues, its for overall server things. If you have any further doubts regarding the matter DO NOT continued the conversation on this GitHub thread, make a #General-support ticket and you will be helped there. 

Kind regards
- Sand Andreas Highway Patrol Lieutenant Alberto Gomez

**Comment by fisheeeee** [comment]
owned
