### ISSUE TITLE
"won" at slots but did not recieve any money

### ISSUE THREAD

**Issue by bublikLV** [fkk-cz/noire-public#251]
The title says it all, I was playing the 250$ slots and did not receive the winnings for matching 3 diamonds.

https://youtu.be/LoAUf7OZJi0   - this is the video evidence, at 2:29 is where I match 3 diamonds.

https://youtu.be/D8DFsCt_pBU - Here is a second video of me showing my inventory because I pressed the save replay button prematurely.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/69df153706da4dfa78ec0e76c4d67a4aab699dc4

Also for some reason all machines had incorrect winning multipliers. Fixed the multipliers so the payouts are closer to what you actually see on the slot machines, with the exception of the 1x match on the right -- that one should not pay 10x.

![image](https://user-images.githubusercontent.com/74131024/144518865-e46d3e5e-dc39-4c23-b39b-1921fe9fecef.png)


@bublikLV what is your steam ID? I'll credit you $250,000 for what you should have won with a 1000x multiplier under the **correct** multipliers.

**Comment by bublikLV** [comment]
My steam - https://steamcommunity.com/id/milkyoface 

Thank you!

**Comment by fkk-cz** [comment]
> My steam - https://steamcommunity.com/id/milkyoface
> 
> Thank you!

Credited your bank $250,000. Your new balance is $353,769. Thanks for reporting this issue!
