### ISSUE TITLE
Bug During War

### ISSUE THREAD

**Issue by ZacksDesign** [fkk-cz/noire-public#310]
So during wars we have this slight issues. 
    When you are at war with a gang while off your whitelist lets say you are on the Landscaping job then you or your gang declares. This will not show up the red box showing you are at war, same when you go back to job center to change back to your Gang WL it will not show that Red Box during war unless you declare again for the individuals that are not yet on the whitelist. Second of all I feel those players that disconnect mid-war or fly-in mid-war that start out on the WL. Lets say I joined the city when we are at war while on my Gang whitelist, this will not show we are at war until we declare again. So each member that doesnt have the Red Box at the top of there screen means we have to redeclare each time it pops up which is frusterating.  
I just think its frusterating that when some members have the RED War symbol and some dont because they might've just flew in during war, get banned for unreasonable situations.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/2d9489696d30f8ae482739b0e2d9b4651373a974.

Also implemented a lot of the changes based on feedback/suggestions in the [discussion](https://github.com/fkk-cz/noire-public/discussions/285):

- Gangs can only declare war at night, between 21:00 and 3:00 (in-game time, obviously)
- Only one active war is allowed at a time
- Wars automatically expire 20 minutes after declaration
- Players who connect in the middle of a war or switch into a gang job involved in an active war will now have the notification displayed, preventing the need to declare multiple times.

I wasn't able to actually test these changes, but they should all work. More to come...
