### ISSUE TITLE
Dynamic store robbery timers

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#437]
Currently, store robberies are very predictable and feel scripted, with players taking (fake) hostages to prevent police entry and subsequently getting into a vehicle (usually the `hayabusa`) to flee.

To spice up these robberies and make them more exciting and fun for both sides, robbery timers should be dynamic and depend on a variety of factors, such as:
- Location of the store or bar/club
- Distance to closest cop
- Jurisdiction
- Number of times the particular place has been robbed today

Ideally, the criminal should be finished with the robbery around the same time the police show up. From a statistics perspective, the criminal should have a 50/50 chance of being able to leave _before_ the police arrive, which would eliminate the need for a hostage. The amount of hostage taking is incredibly excessive and a bit ridiculous, crossing into powergaming territory since everyone is doing it solely to 'win'.

**Comment by Cortez312** [comment]
If the cops do show up and the robbers don't have a hostage then they're pretty much fucked and the new charges will just fuck them to hell if they decide to try to fight the cops. The store robberies payouts are nowhere near the price of the fines you get either.

**Comment by fkk-cz** [comment]
Refer to the last paragraph:
> Ideally, the criminal should be finished with the robbery around the same time the police show up. From a statistics perspective, the criminal should have a 50/50 chance of being able to leave before the police arrive, which would eliminate the need for a hostage.

Hostage 'roleplay' is terrible and usually staged, feels inauthentic, and doesn't offer criminals many choices. Making the robbery timers dynamic should solve _most_ of these issues and allow criminals to have a better chance at making money from going on a store robbery spree.

**Comment by viigyD** [comment]
> robbery timers should be dynamic and depend on a variety of factors

Another possible mechanic could be, the longer a robber stays inside the store, the larger their yield. 
- So say if a crim initiates a robbery and walks right out, they will only get like $250 dirty. If they stay for an additional 10 seconds, they will get $500. And for every additional increment of 10 seconds they will get more money (up to a max). So basically people who wanna do a quick robbery with no hostage, they can do it but won't yield nearly as much dirty cash as someone who gets a hostage and sticks up the store for the full amount of time. This also allows police to determine how much force they should respond with (the longer that crims stay inside, the more resources police can use like highspeed, spike strips, Air1, more units, etc.)
- The amount of dirty cash per unit of time can also depend on the amount of police on duty, the location, time since last robbed, and so on like you suggested. So if there are like 10+ cops on, then walking in and right out might yield $750 dirty instead of $250.

> The store robbery payouts are nowhere near the price of the fines you get either.

I don't think the robbery payout is meant to be balanced out with the possible charges you risk getting. The whole point of the risk is to get dirty cash that can be used to purchase black market items.

**Comment by Creloix** [comment]
thatd be badass.

**Comment by fkk-cz** [comment]
Trying this out in https://github.com/fkk-cz/noire/commit/864c2dc1367575db862588862f22c29981b01e58.

Robbery timers will now be dynamic and are currently based on two factors:
- Distance of the closest cop (with correct jurisdiction, city robberies will check for LSPD and vice-versa for county robberies)
- Number of times that particular store has been robbed in a day

The end result is the time it takes to complete a store/bar robbery has been cut drastically. Stores in populated areas, e.g. 125 car wash, can now be robbed in < 25 seconds. Other robberies in less populated areas will take a bit more time.

Here are some additional changes and fixes:
- Store clerk animations have been fixed and are somewhat synced between players.
- The progress bar has been removed as it makes no sense from a roleplay perspective. An audio cue will be played instead.
- Starting a robbery will require a player to aim directly at the clerk, should help reduce the number of 'accidental' robberies caused by players pointing guns in a store _near_ the counter.

Looking for feedback on this from both criminals/police. This should make robberies more dynamic and exciting. Hostage taking **should** be discouraged, as it's the same cookie cutter shit every time.
