### ISSUE TITLE
i died to locals while inside my house

### ISSUE THREAD

**Issue by JaysTwisted** [fkk-cz/noire-public#489]
https://medal.tv/games/gta-v/clips/7G0tBDMrcUSPd/d1337cYJKqiJ?invite=cr-MSxCV1QsNDM5NjQ1Nzgs

**Comment by RockiBurns** [comment]
That's so broken on so many levels!
Locals being this aggressive, especially at your house, before gangs have the ability to even start missions to improve your reputation with them is ridiculous.

Once we've successfully hit the command to enter houses, we should be in a temporary safe zone. This should be the case because people can't enter our homes to pick us up in situations like the one that happened to you. Only people with keys can enter.

I suggest the temporary safe zone/green zone be connected only to successfully hitting the command to enter a house to which you have keys so it doesn't become an abused exploit where people try to use interacting with the menu for houses they don't own to avoid taking damage in a fire fight.

**Comment by fkk-cz** [comment]
Not sure what you are trying to report here. Watching the video, there were no NPCs inside your house, you were killed after teleporting inside.
