### ISSUE TITLE
PDM menu organization and search bar

### ISSUE THREAD

**Issue by fkk-cz** [fkk-cz/noire-public#508]
A new PDM menu should allow players to search vehicles by make, model, and year, with partial matches.

In addition, should probably fix https://github.com/fkk-cz/noire-public/issues/373 as well.

**Comment by ThatDudeJakeGaming** [comment]
I've also been working on grading them, if you want to add that in, as well?
I'm about 35% through the entire list of vehicles, so far....

**Comment by ThatDudeJakeGaming** [comment]
Finally Done with the lists....  I set them up as PDF's
[Non-Supporter Car Classes.pdf](https://github.com/fkk
[Supporter Car Classes.pdf](https://github.com/fkk-cz/noire-public/files/7962364/Supporter.Car.Classes.pdf)
-cz/noire-public/files/7962363/Non-Supporter.Car.Classes.pdf)
.

**Comment by cxerq** [comment]
> Finally Done with the lists.... I set them up as PDF's [Supporter Car Classes.pdf](https://github.com/fkk-cz/noire-public/files/7962368/Supporter.Car.Classes.pdf) [Non-Supporter Car Classes.pdf](https://github.com/fkk-cz/noire-public/files/7962372/Non-Supporter.Car.Classes.pdf)

So how did you do this exactly cause I dont understand why the Non support R8 is B+ tbh so im curious!

**Comment by ThatDudeJakeGaming** [comment]
The Non-Supporter I graded on a separate level, because of DSC function not working for about...  90% of the vehicles?  But I had a route that I would run on the Military Airstrip, as well as a secondary speed test.  I plan on grading vehicles all on the same spectrum, later on, but at the moment I'm burned the hell out.
Supporter B and C Class have 77 Vehicles EACH, so you can understand how it can tire someone out just driving each individual Vehicle.
Also, Motorbikes have not been graded yet, due to Motocross series vehicles being a separate class on it's own.  But it shouldn't be hard to figure which ones are M series, M+, and M++.

**Comment by ThatDudeJakeGaming** [comment]
But if you want to see the course that I essentially established, I'd be more than happy to show you, once I'm in the city.  It tests Acceleration, Speed, Handling, Grip, Hard Braking, Soft Braking, and Recovery.
Where as the Top Speed test....  Well...  That should be self-explanatory. xD

**Comment by MrThrawn** [comment]
Holy crap- great work with the lists , this will be a wonderful quality of life upgrade
