### ISSUE TITLE
UI blocks photo when selling

### ISSUE THREAD

**Issue by AustinM0527** [fkk-cz/noire-public#572]
The new UI looks great. only downside is when selling, when you get your buyer the UI blocks a good portion of the picture making it a challenge to figure out which person you got,

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/87ed543af87f677e7bc28340b609d0064729e7fc.

Tried experimenting with moving the HUD, the bottom left corner seems to be the best place to anchor it.

Added a workaround where certain notifications (ones with mugshots or other icons) will temporarily hide the HUD. This applies to the vehicle HUD as well. Unfortunately this will not apply to simple text-only feed notifications, but it's better than nothing.

**Comment by fkk-cz** [comment]
The applied fix seems to be inconsistent, further investigation is needed.
