### ISSUE TITLE
DOJ Court Upgrades

### ISSUE THREAD

**Issue by tythetanman** [fkk-cz/noire-public#648]
I enjoy the court system and what it’s been developing into, BUT I do have suggestions to better the judicial system to help the city.

**Civil court system** to be able to give payouts and limit the max total given to citizens of the city, so it’s not insane. (Number one request from anyone who discusses the court system, along with open court days.)

(Would need a safe to support it with a set total and budget for payouts on civil cases.)

**Parking for DOJ** (has been discussed in the last 2 months) that only LEO’s and DOJ staff can enter (possibly across the street with a gate)

**Soundproof Interior** for 585 courthouse for private matters between LEO’s and attorney/clients.

**New Pay grades**

Judge: $4000
SA: $3500
1st Seat Attorney: $3000
2nd Seat Attorney: $2500
Paralegal: $1000
Clerk: $2000 we currently have the clerk position at the defense attorney position for a better pay because of the $500 an hour that matches unemployment with the hard work they do.

Pay suggestion by SA Ethan Go and supported by each SA and Judge on staff.

**A working court safe** for court fees that are assessed that we cannot touch currently and whenever we force charge it does not add it the suspect or potential suspects have to press guilty.

All suggestions discussed by the DOJ staff.

**Comment by teresgrunt4555** [comment]
Another thing we need to talk about is either getting one person that has access to a taser and handcuffs so we can move people freely from cells when we get an overwhelming amount of people or getting marshals full time when court is open. This would help us improve the DOJ and keep everything moving smoothly and quickly.

**Comment by fkk-cz** [comment]
> Soundproof Interior for 585 courthouse for private matters between LEO’s and attorney/clients.

Audio occlusion is fixed for the courthouse, with the exception of the long hallway connecting the courtroom and conference room. Tested everywhere else it seemed to be fine.

**Comment by MatticusDaGreat** [comment]
We also need a lock placed on the Judge's Quarters behind the Judge stand, with only Judges and State Attorneys having access. Thanks in advance

**Comment by fkk-cz** [comment]
Occlusion is fixed for the entire courthouse, apparently I was missing an `InteriorName` entry for the hallway/corridor.

https://github.com/fkk-cz/noire/commit/feab1407a0c053fa3c95ac47b5de323ba05ab4a2

> We also need a lock placed on the Judge's Quarters behind the Judge stand, with only Judges and State Attorneys having access. Thanks in advance

https://github.com/fkk-cz/noire/commit/ff16a8ff458654aec577d0f745bc027c22a85dd4

Added as well.

**Comment by tythetanman** [comment]
Thank you for the garage.

**Comment by mfried456** [comment]
Would love to see a change to the pay as mentioned above. Additionally, having a way for defense attorneys to invoice clients on the spot to ensure payment for services. As of right now, attorneys are required to bring a client to the bank to get paid, which is problematic at times. Thanks

**Comment by RockemRobotics** [comment]
> Additionally, having a way for defense attorneys to invoice clients on the spot to ensure payment for services.

As I said in the other thread, I totally agree here. We pushed for invoicing ability early on but the rationale for not providing it was that the attorneys could abuse it. At this point, since the city can trust bartenders, valets, and others to responsibly use invoicing, it feels like a slap in the face to say that DOJ attorneys cannot be trusted with it.

**Comment by tythetanman** [comment]
OK, so I get kidnapped, and I die way too many times on shift as judge. Like for example right now I'm dead and there's multiple people in the cells for the courthouse. 

They have to wait a long amount of time whenever I die, and it's happened a lot, is there anyway we can get a kill switch if there's only like one or two people on to be able to convict I'm the only one right now on and people still come in because there's no kill switch to close court.

**Comment by cxerq** [comment]
> 

Well thats stupid that you get killed/kidnapped alot while on duty! There should be some cop there at all times really when court is open!

**Comment by RockemRobotics** [comment]
Not to mention that since the only way we can close court is to clock out, and that requires going from deep inside the courthouse to the front lobby. That is enough time for people to show up to the back cells, which means we have to keep court open to deal with them or they will be stuck indefinitely.

And we cannot have meetings or hold a trial without the back cells filling up because court is "open" while we work no matter what.

**Comment by ItsGabble** [comment]
I've been in the cells of court when it gets stacked 2-3 deep per cell. Feels like they could use a cooldown button like PD and HP have.

**Comment by RockemRobotics** [comment]
Re-upping some of our DOJ requests.
- Ability to close court without clocking out (i.e. force cooldown)
- - We still cannot close court without every DOJ leader clocking out and losing our key access. This means people can still get bussed into the cells while we try to clock out, and at times the cells get overwhelmed with huge numbers of people in a very short period of time. If HP and PD can force cooldown to deal with big events, I don't know why DOJ can't do the same.
- Ability to actually access/pull money out of the DOJ safe. 
- - Not once since the safe was put in place months ago have we been able to pull money out of it. It's not worth charging people court fees because the money just sits there and cannot be touched.

**Comment by tythetanman** [comment]
Adding a small note to this:

Just a suggestion, really. Putting that unimpound Location from in the courthouse and transferring it to DOT.

Then when someone requests a car to be released, and we know if the charges were dropped or not, they communicate with us, and we tell them if the charges were dropped and a decision on that.

Also paying attention to the amount of impounds that are done. The majority of them are done by DOT and are not crime related.

It would also encourage communication between the two departments and more interactions with DOT and give us more chances to be able to do more things in the court system like handle suspects and actually potentially have open court without having to handle the discussion of releasing someone’s vehicle while in court.

**Comment by RockemRobotics** [comment]
Re-upping some of our DOJ requests.

- Ability for attorneys to invoice other people for their services.
- - With no ATM, no way to pull out court fees, and no invoicing, there is NO reliable way for our attorneys to get paid for their services as public defenders. They regularly get skipped over for payments and it's generating a lot of burnout.

- Ability to actually access/pull money out of the DOJ safe.
- - Not once since the safe was put in place months ago have we been able to pull money out of it. It's not worth charging people court fees because the money just sits there and cannot be touched.

- Ability to close court without clocking out (i.e. force cooldown)
- - We still cannot close court without every DOJ leader clocking out and losing our key access. This means people can still get bussed into the cells while we try to clock out, and at times the cells get overwhelmed with huge numbers of people in a very short period of time. If HP and PD can force cooldown to deal with big events, I don't know why DOJ can't do the same.

**Comment by ChirpyMedusa** [comment]
On the DOJ safe: It is silly that the reason we can't pull money out is because of a simple bug. SA's and Judges are able to assess court fees, see the total balance, and even enter an amount. The only thing that doesn't work is when someone presses withdraw no money actually withdraws. This seems like something that could easily be fixed and would make the lives of DOJ easier. Thank you in advance.

**Comment by RockemRobotics** [comment]
Re-upping some of our DOJ requests.

- Ability for attorneys to invoice other people for their services.

-- With no ATM, no way to pull out court fees, and no invoicing, there is NO reliable way for our attorneys to get paid for their services as public defenders. They regularly get skipped over for payments and it's generating a lot of burnout.

- We still cannot close court without every DOJ leader clocking out and losing our key access. 
-- This means people can still get bussed into the cells while we try to clock out, and at times the cells get overwhelmed with huge numbers of people in a very short period of time. If HP and PD can force cooldown to deal with big events, I don't know why DOJ can't do the same.

**Comment by mfried456** [comment]
Re-upping some of our DOJ requests, as we have been waiting a long time for these to be implemented:

1. Ability for attorneys to invoice other people for their services.
- With no ATM, no way to pull out court fees, and no invoicing, there is NO reliable way for our attorneys to get paid for their services as public defenders. They regularly get skipped over for payments and it's generating a lot of burnout.

2. We still cannot close court without every DOJ leader clocking out and losing our key access.
- This means people can still get bussed into the cells while we try to clock out, and at times the cells get overwhelmed with huge numbers of people in a very short period of time. If HP and PD can force cooldown to deal with big events, I don't know why DOJ can't do the same.

These two changes would greatly improve the DOJ. Thank you in advance for your time.

**Comment by No-Yes1** [comment]
Please stop with the "re-upping"/ bumping of these requests, there is a lot of suggestions/upgrades that are being requested. You just have to remain patient.

**Comment by mfried456** [comment]
I think civil lawsuits should be implemented in the DOJ. With the introduction of multiple businesses throughout the city and business licenses, more civil lawsuits will arise and need a fair and impartial way to deal with them. 

I know that civil lawsuits have been problematic in the past due to individuals wanting to sue PD, but if we were to limit lawsuits to civ vs civ that have proper basis and sufficient evidence to support claims, it would be a great way to resolve disputes and add more RP to the city.

**Comment by RockemRobotics** [comment]
> I think civil lawsuits should be implemented in the DOJ.

There is overall support from PD, HP, and DOJ to bring back civil suits to some degree. Unfortunately, we (the DOJ) were given standing orders to stop all civil suits and have never been given permission to bring them back.

**Comment by tythetanman** [comment]
Audio occlusion At 143 courthouse definitely needs fixing because you can hear everything. 

You can also get through the Front door by going into the side left of the entrance door corner. Just jump.

**Comment by fkk-cz** [comment]
> Audio occlusion At 143 courthouse definitely needs fixing because you can hear everything.

Fixed in https://github.com/fkk-cz/noire/commit/c5015258fa7ad3ceb11600be06e0f5195645eed3.

> You can also get through the Front door by going into the side left of the entrance door corner. Just jump.

Screenshot/video needed.

**Comment by RockemRobotics** [comment]
> Screenshot/video needed.

https://streamable.com/3wqukr

**Comment by tythetanman** [comment]
This is more of a need for many parts of the city not just court, but I’m putting it under court because it is something that I do have the ability in the city to be able to press to be able to force charge for this or these things.

I did have the discussion with Bobby/Lt Amiri about this, and just making sure it is not forgotten because it is something like I said that impacts many parts of the city.

Whenever the court Judge's/SA's force charge, and I have not done this in several months for this reason. The money goes poof for different parts of the city, like:

*Court fees
Burger Shot meal invoices
Taxi fare
VU entry fees
Bahama Mama
Cockatoo
Maisonette
Comedy club
Galaxy club
Gang fees (not as often as of recent)

(VU two major events this week and would be a financial impact with fees that sit like some have for months)*

If I were to find someone guilty or in that case force charge, the money just goes poof. And it’s a ton of missing income that just disappears and that’s my reasoning for not pressing it, and they just sit on a lot of people because they do not go to the correct society fund or go to society funds at all.

**Comment by teresgrunt4555** [comment]
We really need a way to fix all the unpaid invoices
