### ISSUE TITLE
DOJ restructuring 

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#670]
Hey, just bringing this up as it’s something I noticed that can be done better, right now the DOJ has more power and access to information then it should. Judges and state attorneys should not be hiring defence attorneys along with various other issues. The few suggestions I have to enhance role play as well as objectivity within the server include the states attorneys being paid and hired by LSPD and HP as well as the defence attorneys being hired somewhere separate and outside of judges and state attorneys. Right now the DOJ currently does great things however there is a bias and lack of objectivity that comes into play sometimes. Things can skew public records including judges/state attorneys finding people guilty for simple charges that can be handled at the 211 court house which will raise the amount of convictions that a judge has given out which can eliminate questions of bias in certain instances where bias may be present. I know some of these changes can’t and won’t happen overnight and I also know personally that this change and possible restructuring is something that is better with more input then just my own. Saying all this I ask that you add your input because at the end of the day the DOJ is added and designed for objectivity and equality in the server and shouldn’t act as a system that finds people guilty/not guilty without proper objective reasoning. These changes without a doubt are complicated so my suggestion for the meantime while more input other than my own is given is I would suggest that the DOJ and its employees including judges, states attorneys, defence attorneys and clerks are all reviewed by an entity outside of the DOJ on a semi regular basis this would allow the court to run smoothly with no question of bias and implementing public court and/or jury’s would add more role play plus less bias as proceedings would be in the public display.

**Comment by tythetanman** [comment]
Court activities are already public to the entire city and verdict’s

If anything the court system doesn’t have enough access. Simple things like civil court in all honesty should be a priority before anything else because that’s actually the most requested thing that citizens of the city ask for. 

As far as everything above that’s not a github request that’s more of a thing you would bring up as adjustments to policies in the city. 

I could be wrong thought.. that is something you would go to hire ups about not in a area where you make suggestions about different things for the court like maybe a MDT change and adjustment or things of that nature.

**Comment by tythetanman** [comment]
We now submit reasoning for drop charges in reports that is actually something that was added while you were away this last weekend. 

Different adjustments are made and we have chats and discussions with the proper people in the city to be able to handle those things we are monitored more than you think especially whenever convictions are public to the entire city.

**Comment by RockemRobotics** [comment]
> Hey, just bringing this up as it’s something I noticed that can be done better, right now the DOJ has more power and access to information then it should. 

Debatable. There are a lot of things we're expected to do that we actually do not have the power to carry out, including the ability to charge and arrest on-duty LEOs, deal with civil suits, and more.

> Judges and state attorneys should not be hiring defence attorneys along with various other issues. 

I've said before in DOJ meetings that realistically, Judges, SAs, and Defense Attorneys wouldn't be in the same hierarchy, but that here in the city we're doing what we can to make it work because we're all on the same side when it comes to allowing justice and RP.

> The few suggestions I have to enhance role play as well as objectivity within the server include the states attorneys being paid and hired by LSPD and HP

Wait, you think this would _enhance_ objectivity? If anything, it would increase bias.

> as well as the defence attorneys being hired somewhere separate and outside of judges and state attorneys. 

While upper DOJ leadership does take the first look at applicants, all defense attorneys get a chance to interact with them and provide feedback before they are fully brought on. For having non-DOJ have a part in hiring DOJ staff - that's something that no other whitelisted job does in the city, and is untenable for us as well.

> Right now the DOJ currently does great things however there is a bias and lack of objectivity that comes into play sometimes. Things can skew public records including judges/state attorneys finding people guilty for simple charges that can be handled at the 211 court house which will raise the amount of convictions that a judge has given out which can eliminate questions of bias in certain instances where bias may be present.

We do get accusations of bias, yes, but so does every other whitelisted job (particularly LEOs). The big difference is that we have public records, as you mention, that everyone can read through. We've found through experience that despite what you are saying regarding conviction records, people tend to only focus on the case dismissals when accusing us of bias.  I've always encouraged everyone who has an issue with any dismissal or conviction to come to the courthouse and speak to us directly, and we can discuss like adults any problems. We've also started taking notes in arrest reports whenever any charges are dismissed so that there is a paper trail to maintain and uphold our position as unbiased purveyors of justice.

> I know some of these changes can’t and won’t happen overnight and I also know personally that this change and possible restructuring is something that is better with more input then just my own. 

I'll admit that I'm not good at always focusing on improvements because sometimes we need to let things settle out to determine if they work or not before making further changes. All the same, we do accept feedback and I love hearing from our working DOJ employees about ideas they have for changes and improvements based on their experiences.

> Saying all this I ask that you add your input because at the end of the day the DOJ is added and designed for objectivity and equality in the server and shouldn’t act as a system that finds people guilty/not guilty without proper objective reasoning. 

We do our best to use objective reasoning - within reason. We RP when possible, look at evidence, and try to get people out of the court system and back on the streets quickly. The city does everything at an accelerated timescale (the longest possible jail sentence is 2.5 hours IRL, the average is more like 30 minutes), so the guarantee of a "speedy trial" means something very different here from what it means IRL.

> These changes without a doubt are complicated so my suggestion for the meantime while more input other than my own is given is I would suggest that the DOJ and its employees including judges, states attorneys, defence attorneys and clerks are all reviewed by an entity outside of the DOJ on a semi regular basis this would allow the court to run smoothly with no question of bias

What entity would review DOJ? We are open to the public and invite anyone to come talk to us regularly. On top of that, as you said, our conviction/dismissal records are open to the public, so we are _constantly_ under review.

> and implementing public court and/or jury’s would add more role play plus less bias as proceedings would be in the public display.

As I said before, the guarantee for a "speedy trial" really impacts us here. We don't get many people coming through the courthouse who would want to spend 2+ hours in court for a jury trial to fight a 36-month (36 minute) robbery charge or even a 120-month (2-hour) capital murder charge. We're open to considering it, but because people will **still** get transported to the courthouse while the trial is running, we know from experience that it causes more issues than its worth.

---------------------------------------

All in all, we do appreciate feedback, and I like having discussions about how to improve the DOJ. But for most of these points if you had brought them straight to us I could have enumerated all of the above to you in person rather than typing it all out for the entire city to see.

**Comment by Mynameisnotlenny** [comment]
All in all I like where this conversation is heading, my reasoning for bringing this up here is so that the rest of the community can have a chance to give their own ideas to see what as a community is the most logical and beneficial for the server. I think handling cases with fines over a certain amount of money in public view in a safe zone area where everyone besides the involved individuals are force muted is one potential idea, this would allow more transparency with trials that end up costing people large sums of money and would allow more for people to do and see in the city. Regarding an entity outside of the DOJ I believe community moderators with solid and objective track records should periodically review staff within the DOJ or something along these lines. Touching on your points about hiring outside of the DOJ and LSPD and HP hiring state attorneys, the reasoning this would increase objectivity is because it separates the judges from the state attorneys and removes the ability for states attorneys to convict/dismiss charges which allows the judge to look at the facts of a case without having the judge and state attorneys together making executive decisions, this is because at the end of the day all a state attorney should be doing is fighting on behalf of the officers and their reports as well as fighting on behalf of the state while the judge try’s to determine whether the case and details within are plausible and if reasonable doubt exists. The states attorneys should go back and forth with defence attorneys to try and come to a mutual agreement then the judge can decide wether they agree or disagree with the decision between the defence and state attorneys or if no agreement has been made the judge can be the deciding vote/ final word on what charges the offender receives. This can still be done in a quick and timely matter and really keeps objectivity at the forefront as both sides are arguing on details of the case with a judge as a mediator instead of a defence attorney arguing against a judge or state attorney then the state attorney getting final say when the judge should be the one who decides. I would also like to apologize for the formatting of this as I am on mobile and it may be hard to read but also wanted to add that civil suits would be great however I believe they should be something separate from criminal court as they’re separate practices of law. Opening a civil court that is open on certain days would definitely be interesting and would also enhance role play. Adding in a special investigation unit to audit police, ems, dot and potentially DOJ with the results from investigations being public to the city or the individuals involved would probably be one of the best ways to increase objectivity and is something that is present in the majority of police departments and would exist in different forms for the other public services as well. Adding to this having reports handled by a variety of people and not just the individuals in the profession in higher position but rather as a group with group votes would allow things to be clearing and wouldn’t allow individual bias to influence results of investigations

**Comment by MatticusDaGreat** [comment]
**- I think handling cases with fines over a certain amount of money in public view in a safe zone area where everyone besides the involved individuals are force muted is one potential idea, this would allow more transparency with trials that end up costing people large sums of money and would allow more for people to do and see in the city.**

We don't have public trials anymore based on trials we've had in the past. When we had public trials, it always ended up with a dozen or more people being arrested or given community service because the audience could not behave properly and just observe. If we do have any sort of public trials in the future, there will be very limited seating available. 

On another point, these public events take significantly longer than expected 80% of the time, whether it be in preparation time, time spent identifying or gathering witnesses, etc. It would be a fun RP experience in theory, but all of these things combined make it not such a fun experience for DOJ or the audience that is well-behaved.

**-  Regarding an entity outside of the DOJ I believe community moderators with solid and objective track records should periodically review staff within the DOJ or something along these lines.**

I'm 1000% for the existence of some sort of Internal Affairs for DOJ, LSPD, SAHP, etc., but it should be handled in-city by impartial third-parties. Community moderators are not impartial third-parties, as many of them are in the organizations that would be under scrutiny by IA. The other issue with IA would be the quality of individual hired. How does one determine who is fit and impartial, yet has enough time and experience in the city to understand the processes in place in each organization well enough to analyze them?

**- Touching on your points about hiring outside of the DOJ and LSPD and HP hiring state attorneys, the reasoning this would increase objectivity is because it separates the judges from the state attorneys and removes the ability for states attorneys to convict/dismiss charges which allows the judge to look at the facts of a case without having the judge and state attorneys together making executive decisions....can still be done in a quick and timely matter and really keeps objectivity at the forefront as both sides are arguing on details of the case with a judge as a mediator instead of a defence attorney arguing against a judge or state attorney then the state attorney getting final say when the judge should be the one who decides.**

What you said is already how this works. The judges take inputs from state attorneys, but in no way does this mean that the state attorneys get the final say in a case. It is a judge's job to hear input from all parties, and the judges and SAs have on-going discussions specifically pertaining to maintaining a separation of duties and responsibilities. When present, judges in the city always have the final say in criminal cases. The **_only_** exception is when a judge specifically delegates authority to hear and rule on cases to a state attorney during times of heavy traffic in the court.

**- Opening a civil court that is open on certain days would definitely be interesting and would also enhance role play. Adding in a special investigation unit to audit police, ems, dot and potentially DOJ with the results from investigations being public to the city or the individuals involved would probably be one of the best ways to increase objectivity and is something that is present in the majority of police departments and would exist in different forms for the other public services as well. Adding to this having reports handled by a variety of people and not just the individuals in the profession in higher position but rather as a group with group votes would allow things to be clearing and wouldn’t allow individual bias to influence results of investigations**

Again, I'd love to have an Internal Affairs organization, but until it can be done in a way that is appropriate and practical for the way the city operates, I'm not sure if it can be implemented. I do hope that we're able to figure it out for the future though. The DOJ is already working towards being as transparent to the public as possible, with discussions of releasing the Code of Laws to public read access, as well as already having all convictions and dismissals public. We are also now including notes in police reports where we dismiss charges in an attempt to let the LSPD/SAHP know why we are dismissing certain charges.

**Comment by No-Yes1** [comment]
You already have an existing issue relating to DOJ upgrades: https://github.com/fkk-cz/noire-public/issues/648. Use that only. No need to make multiple issues.
