### ISSUE TITLE
AMR Fixes/Enhancements

### ISSUE THREAD

**Issue by woody67890** [fkk-cz/noire-public#704]
Over the past month, I have been putting together a list of ideas and issues that I have come across to improve AMR especially since the name change. I don't believe AMR/EMS has had any major updates/upgrades for a while and it is getting stale. More abilities would encourage more applications and may balance out apps across the whitelist jobs and legals.

Fixes-

1. Allow AMR to open up doors while off-duty so we can access the clocking in terminals and locker room (Zonah).
2. Allow AMR to open up MRPD gate/doors and SAHP gate/doors as we can't access anyone that goes down in there unless someone lets us in.
3. Add a panic button (similar to that of LEOs) that AMR can press when in danger instead of going through the F6 menu which takes time and doesn't always send a distress signal. 
4. Send an immediate distress signal to the entirety of AMR is an EMT is downed. EMTs are usually the first people that walk into the aftermath of any shootings or gang related fighting and there may not be time to send a distress signal. 
5. Give AMR the ability to see LSPD and SAHP blips on the map so if we need assistance or waiting for assistance, we can see how close LEOs are to help.
6. Fix the trunks on the Tahoe, Explorer and Ford 250/350 so we can store food, drinks, phones and repair kits (allow the contents to stay when putting the vehicles away).
7. Fix the names of the Tahoe, Explorer and Ford 250/350 so they are labelled as 'NULL' and we can see what vehicle we're pulling out of the garage.

Enhancements-

1. Can the current fleet of AMR vehicles have an update/rework? The current ambulances have terrible braking and can be easily flipped if hit by another vehicle (and then difficult to flip leaving EMT stranded). Again, after the name change to AMR, would be nice to continue the new image across vehicles too. Found these-
https://www.gta5-mods.com/vehicles/freightliner-sprinter-los-santos-blaine-county-ambulance-els-lods
https://www.gta5-mods.com/vehicles/ford-e450-lafd-ambulance-4k-by-pimdslr
3. Additional certifications - at the moment, we have limited certifications (FTM/Pilot) and it would be good to have an additional 'Water Rescue' one as we get calls when people are in water/deep water. This would involve an extra EUP with a scuba suit/rebreather so AMR can stay under water long enough to get the bodies.
4. In addition to the above, another cert for a 'First Responder' so a Senior EMT who would have the ability to 'revive' people on the scene of any code 3 LEO assistance instead of taking them to Pillbox and locking doors. That way the criminal can be taken by PD straight away.
5. Additional hospital roles (similar to other cities) and different hospital interiors , especially for Pillbox where people will come back to life on a bed, instead of stood up in the middle of the ward. This would obviously require more research into scripts/interiors, but happy to do the research if it would be a possibility.
6. Reworking the F6 menu. Like LEOs now have the left-alt options, but EMTs still have to go through the F6 menus which takes time and is now 'outdated' in comparison to other left-alt actions.
7. We get a lot of people that 'fly out' once they go unconscious to cut down the timer, but we don't know that they flew out and have to 10-0 (body missing) a lot of call-outs. It would be really great to have some mechanism that cancels our call-out so it's not a wasted journey. It would also be beneficial to give a penalty for people doing this just so they can shorten the wait (fly out dead, fly in dead).

I understand you are really busy and have a long list of improvements/fixes already, but it would be nice to have some improvements to AMR since there has been so many for PD/SAHP/DOJ recently. Thank you! :)

**Comment by woody67890** [comment]
I have thought of another enhancement that would be really helpful- to move the repair spot at Pillbox to the main entrance near where the vehicle spawn. This spot would be more convenient. Thank you

**Comment by WaywardCanuck** [comment]
With the addition of the new Yacht I feel like dive suits/rebreathers are needed now more than ever. Possibly even a vehicle spawn point for a zodiac by the Del Pero Pier to get out to the boat quicker.

AMR name change. It has been brought to my attention by Judge Ty McNugget that "AMR" is a private medical response company run out of the state of California. Due to this when an EMT is murdered the guilty party can't be charged with capital murder, or attempted capital. I would like to see the name changed to either SAMS or SAMR; personally I prefer SAMS.

Better GPS, persistent GPS pings, and mini GPS while on foot. This is a two prong approach to the GPS, one is to have the GPS let EMT's know if the ping is upper or lower, have the ping stay on our GPS until we clear it ourselves, and finally having an active GPS while we're on foot would allow us to see where the ping is without having to stop to look at the map.

This one you already know about, but a Heli that can have a stretcher loaded into it like the ambulances. Having the stretcher sticking out of the front of our MedEvac looks terrible.

Speaking of the Heli's it would be nice to have Heli pads at Pillbox, Mount Zonah, Sandy Shores Medical, and the new Paleto hospital. Some of the people in the city are real cunts and think it's fun/funny to ram their cars into our heli's to make them break.
