### ISSUE TITLE
Mining glitches 

### ISSUE THREAD

**Issue by Bane1221** [fkk-cz/noire-public#708]
Trucks will randomly despawn when your mining and spawn somewhere else, Dump trucks will fly into the air and land on top of trailers. Trailers will fly into the air and land upside down or right side up if you lucky . https://www.youtube.com/watch?v=zlmgtG8EJe0 
https://www.youtube.com/watch?v=6_8i5Bgnkxk Dont blink you might miss it.

**Comment by mystic04** [comment]
yup , i fell through the map and when i came back all my shit was flipped as well

**Comment by fkk-cz** [comment]
Added the entire mining zone to the no-vehicle-gen list. Should be better tomorrow. Still highly recommend detaching your trailer if you exit your vehicle, to prevent https://github.com/fkk-cz/noire-public/issues/706 from occurring.

https://github.com/fkk-cz/noire/commit/71549a6385c3f440c57eeb6ad9d25deaf7cfdfe8

**Comment by Dallasknight** [comment]
I know that when a different person gets in the drivers seat the trailer bugs out in the original drivers eyes. So they have to unhitch the trailer. But even then that doesn’t always work. I’ve pulled my trailer out both in my personal garage and in the public and as I’m loading my fjs on the trailer the whole thing disappeared and would be sent to insurance. The only way I could fix the whole trailer driving beside the truck was to put it up in the garage again.

**Comment by Bane1221** [comment]
no-vehicle-gen list does that mean that the NPC Vehicles wont spawn anymore in the mine? If so I think that's a good solution

**Comment by fkk-cz** [comment]
> I know that when a different person gets in the drivers seat the trailer bugs out in the original drivers eyes. So they have to unhitch the trailer.

Yeah that's ..not a good idea given the fact the issue seems to occur when migrating ownership of the trailer between players. When the trailer is in a glitched state (i.e. sideways, still attached but not aligned to the vehicle properly) the best practice is to attempt to connect the trailer with a _different_ vehicle.

Not an ideal solution, especially if no secondary vehicle is available, but better than going to insurance.

**Comment by fkk-cz** [comment]
Due to an obvious oversight, vehicles spawned at a personal garage were being created as automobiles, regardless of whether the vehicle model is one or not. This has been fixed in https://github.com/fkk-cz/noire/commit/2861ad45c415f04c255d9494ad7f07688d4fcf83. Should help fix the flying trailer issues that people have been reporting recently. Probably related to https://github.com/fkk-cz/noire-public/issues/706 as well, as that specific trailer wasn't causing _that_ many issues before.
