### ISSUE TITLE
Supporter car re-sale

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire-public#728]
I guess this would fall in-line with the mileage/depreciation conversation also, but any chance we can get a system to sell supporter vehicles to other supporters? 

1) It would be nice to get a chance at a 30% depreciation instead of just losing it to PDM
2) If there's a mileage/depreciation system in the works, I think it would make the transition easier for supporter cars

**Comment by AngelofDeathGaming** [comment]
I completely support this. I would love to be able to go around buying other supporter vehicles while being an active supporter myself.

**Comment by Hesh77** [comment]
More beneficial for it to be added. I was looking for the Veyron is 517k and for 70% it would go down to 360k which is 157k. I would say either increase the percentage you get from selling at PDM or add that supporters can sell/buy other supporter vehicles outside of PDM.

**Comment by MinoritySanta** [comment]
I heard some mention in the city that this was being considered?  Any chance we can get the opportunity to sell supporter cars to other supporters?

**Comment by DefineFusion** [comment]
This would honestly be a great and amazing idea. It’ll keep cars in circulation instead of the cars just disappearing and being gone forever. It’ll probably be beneficial for the economy as well. As people would have a wider ranger of vehicles which they can buy and sell.

 Also to add on to what Angelo said, it would be a great show of the benefits of being a supporter since there is such a wide range and variety of supporter cars. It’ll just show and advertise to all of the non-supports all the vehicles that they are missing out on and make them want to get supporter even more. Being able to see all the supporter cars and the cheaper prices you can potentially get for them would likely increase the amount of supports currently.

 Also there are plenty of people out there that have supporter cars and would like to let some go but doesn’t want to lose 30% of they paid for. Futhermore , that 30% of value that is lost when reselling to PDM greatly increases the more expensive the vehicle. If I were to sell a 2 million dollar car back to PDM that’s over $600k lost.

I’m conclusion I feel like this would improve quality of life in the city for many people and many people if not all supports would support this idea. As well as another way to bring in more supporters to the city.

**Comment by Bountyrogger** [comment]
If this were the case I hope they would at least leave the option to still sell back to PDM. I only buy Supporter cars atm so I dont have to deal with UCL and all that stuff and it makes it all hassle free

**Comment by MinoritySanta** [comment]
Ideally yes. Just looking for the option to buy from other supporters in addition

**Comment by DefineFusion** [comment]
Any comments or updates on this?

**Comment by dinmamma100** [comment]
why is no staff commenting
