### ISSUE TITLE
Gold From Mining 

### ISSUE THREAD

**Issue by Ethioking** [fkk-cz/noire-public#735]
For some reason gold from mining has the least value even less than iron, copper, and steel, I don't think it was intended to be that way,
For example, 10 gold which is the max you can hold, give only 900, But from Iron, steel, and chopper you get about 800 from ten, but you can hold 25 max of them which makes them more valuable.
people bring ped cars to mining just so they can leave the gold behind because no one wants it, I think since gold weighs as much as diamond and ruby it should be worth more, or at least weigh less so we can carry more .
And if that can't be done at least give us the option to drop the gold so people aren't clogging up mining deposits with ped cars just so they can leave the gold behind in the trunk.

**Comment by glefave0209** [comment]
Gotta disagree homie.  Mines are congested enough and allowing people to drop things will have people taking up spots for longer.  They will drop everything except diamonds and ruby

Personally I love those ped cars full of gold. I'll take that stuff all day

It takes roughly 15 minutes to mine 1000 inventory. If somebody wants to leave behind 40 gold and save me 15 minutes, I'll take that deal.

Off point, but none the less. What you're suggestion would clog the mines up even more and we don't need that. The PED cars aren't the problem with congestion. Gotta keep the trailers flowing

**Comment by Ethioking** [comment]
I can see why you like the fact that people leave gold since it benefits you, but it does not seem like it was the way it was intended to be, Its Gold we are talking about imagine not wanting gold to the point people are going out of their way to get rid of it.                     
 I'm sure most people would agree since people are going out of their way to bring a ped car after the fact that they already have a trailer there, just to abandon the gold they have collected.
Gold shouldn't be some scavenger commodity, it should be highly valued that's why a price buff or a weight reduction makes sense. 

and about the mine being clogged there is a whole top row where they could add to mine

**Comment by glefave0209** [comment]
I agree with a few things here.  I do find gold valuation low, you're right there, but iron, steel and copper would be too high. You can increase gold, but you'd have to decrease the other stuff and it would be net-zero. Instead of ditching gold in ped cars people would be ditching copper.  So your issue would remain

I do agree there seems to be more room to add miner spots and that's been suggested

However, still vehemently disagree with your main ask of being able to drop minerals.  That would be a disaster

Don't forget mining is the most lucrative job.  Its not perfect, but I don't think we can be asking for a pay raise 😂😂

**Comment by glefave0209** [comment]
Agree with Cobra.  IMO it's not worth the time it takes to drop and re-mine anyways

Top efficiency dictates load as fast as possible, sell as fast as possible and repeat.  I don't think these guys ditching gold are doing themselves any favors as it relates to efficiency

**Comment by Ethioking** [comment]
Dropping it was really a last option suggestion, Not what i really want but I do think gold needs some type of change.
I only recommend it cause we already have people ditching their rigs there, and then we got the flipped Riggs there too and ped cars on top of that. some days it just feels like there is to many ped cars there

**Comment by glefave0209** [comment]
So I'm not sure if your suggestion is just for the immersion, but I'm gonna try and tackle all the angles here

Gold price isn't reflective of real life: Agreed, but the other stuff is too high, so it's probably more trouble than it's worth to fix it.  The net effect is you're getting the money you're supposed to for a full load.  If you're going for trying to get gold up so we can make more money, that's not realistic either.  Miners are well paid

PED cars clogging up mines: Ok sure, but adjusting gold price will do nothing to fix this.  They will just dump the "new gold" whatever the lowest price mineral is

Just for the immersion: Sure, if you're trying to get everything to mimic IRL, I get it.  I just think Mining has other, more pressing issues we could work on first.  *cough cough* goosenecks

Judging by your last post, my assumption is your issue is #2, so again, I'll repeat myself.  Changing the price of gold will not stop PED cars at the mines.  People will just leave copper or iron there instead or whatever the new "worthless mineral" becomes

**Comment by fkk-cz** [comment]
> Changing the price of gold will not stop PED cars at the mines. People will just leave copper or iron there instead or whatever the new "worthless mineral" becomes

Well said. Adjusting gold prices seems rather trivial and will not solve any congestion problem, we have already moved the vehicle generators and dump trucks that spawn there and spread out the spots.
