### ISSUE TITLE
DOJ Defense Attorney Invoice

### ISSUE THREAD

**Issue by mfried456** [fkk-cz/noire-public#742]
Hello,

I am wondering if it would be possible to add the same/similar invoicing system used for bartenders and casino staff for defense attorneys. Currently, defense attorneys rely on good faith to have a client pull money out of an atm outside the courthouse. If a defense attorney could invoice clients on the spot for their services, it would be a much better system. Thank you!

**Comment by ChirpyMedusa** [comment]
This would help a lot.

**Comment by RockemRobotics** [comment]
> I am wondering if it would be possible to add the same/similar invoicing system used for bartenders and casino staff for defense attorneys.

Totally agree. We pushed for that early on but the rationale for not providing it was that the attorneys could abuse it. At this point since we can trust bartenders, valets, and others to responsibly use invoicing, it feels like a slap in the face to say that DOJ attorneys cannot be trusted with it.

> Also, currently the court fees charged to people go nowhere and if they went to a safe where everyone got bonuses at the end of the week would be great.

They do go into a safe, they just go into a safe that no one can pull money out of so it's effectively useless.

**Comment by No-Yes1** [comment]
Use the existing issue #648 regarding this

**Comment by mystic04** [comment]
this invoicing system will really help doj a lot , when we help our clients with cases we sort of have to trust that they will come pay us for our services and almost no one does . invoicing system will really help fix this . please and thank you (:
