### ISSUE TITLE
exporting gas from station not working 

### ISSUE THREAD

**Issue by Mynameisnotlenny** [fkk-cz/noire-public#747]
Bought my gas station a couple days ago and have tried exporting gas a couple times to see how it works, however every time I’ve exported gas it just takes the fuel out from the station but then gives no money or location to export the fuel to.

**Comment by tythetanman** [comment]
I have the same problem and I would absolutely love to be able to purchase gas off of Lenny.

**Comment by Mynameisnotlenny** [comment]
Also want to add that I have tried again today to export fuel with similar results. It’ll set the waypoint to deliver the fuel however no truck spawns so you end up just loosing the fuel in the station with nothing in return.

**Comment by Mynameisnotlenny** [comment]
Tried exporting gas today and ran into the same issue of it giving a destination but not spawning any vehicle just wondering if there was any update on this as it would be nice to be able to export gas from the stations

**Comment by hmu4green** [comment]
I have the same problem, when I export it doesn’t spawn any vehicle for me; it only comes up with a waypoint. Drive to the waypoint and nothing happens. Wastes my gas every time I try and do it. Would love this to be fixed

**Comment by iGotDank** [comment]
Unfortunately this issue is still happening, would love to see a fix as this is very inconvenient to gas station owners. I’m sure I speak for Lenny here when I say that we love this server so much we chose to invest a substantial sum of money into these stations, to have this export feature not working highly prohibits us from seeing a return on our money for quite awhile, which I think isn’t necessarily right. I don’t feel as if we’re asking for a lot, simply a bug fix for something that should be working

**Comment by robbieshoff** [comment]
i am pissed they took it out all i want to do is take my truck to the sandy car wash and now its gone :(

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire/commit/750419e0851ae4727ad61c1f2e8a54eb9c0cf6a2.
