### ISSUE TITLE
Cars on trailers randomly Poofing

### ISSUE THREAD

**Issue by PsychoticCore** [fkk-cz/noire-public#815]
You could be mining or just driving down the road and a car will just randomly disappear from your trailer (normally the last one) heres an example
Ive had this happen several times and is not the greatest thing cause you then have to go claim your car at insurance go get it bla bla bla you get it

https://user-images.githubusercontent.com/69283872/167318381-3fb22ffd-5e56-48ed-bac0-6246bed25d8c.mp4

**Comment by fkk-cz** [comment]
This video isn't very helpful, especially without any repro steps or further information. Attached vehicles only get deleted if a) explicitly done so by the server or b) if the entity attached to is deleted. In this case your trailer still exists, along with the other vehicles, which makes it even more unlikely this is caused by any client/server scripts.
