### ISSUE TITLE
Gang zones And Drivebys

### ISSUE THREAD

**Issue by CjSSB13** [fkk-cz/noire-public#828]
I think it would be cool if yall can add in gang zone/ turf wars. i think it would add alot more rp to the city if we were able to do drivebys at gang blocks too which would make it more realistic. im pretty sure all gangs would love to get this added :)

**Comment by ckmoney4** [comment]
If they implement it, Gangs only should have 2 maximum territories. One is their original turf and the other one is if u wanna takeover a turf from other gangs.

**Comment by PreacherDeimos** [comment]
Allow gangs to do drive-bys but you can only shoot in 1st person, this would nerf how OP drive-bys are a lot.

**Comment by PreacherDeimos** [comment]
Here is also an amazing example of where some of these gang wars/ turf wars could take place. 

![image](https://user-images.githubusercontent.com/103844484/168403673-874fc4e2-03af-49af-a29e-3d4839829aea.png)

**Comment by fkk-cz** [comment]
This is an extremely idealistic mindset if you think we haven't tried this before. Already there are issues with gangs refusing to stay in certain gang territory (think Forum Dr./Grove St.) and 'hiding' during active gang wars.

Allowing drivebys would only work if people respected this rule and actually stuck to these high crime areas. Otherwise, it would open up further issues with RDM or crimes in unrealistic areas.

**Comment by CjSSB13** [comment]
so it wouldnt be gang stay in gang zones it would be gang defending there
gang zones. so if they claim an opps gangzone they would be rewarded with
dirty and clean money a certain amount. the driveby thing  you can make it
where gangs can only do it in gang zone so u can only driveby at gangs like
in big city

**Comment by dgreengoblin** [comment]
Allow gangs to sell on their block would be a great way to get this started

**Comment by CjSSB13** [comment]
I agree!
