### ISSUE TITLE
Car Thefts 

### ISSUE THREAD

**Issue by TdotG** [fkk-cz/noire-public#859]
Idk if it's just happening to me but lately everytime I steal the car and return it to the drop off point. The drop off point vanishes into thin air and i get nothing for it. Its happened to me the last 5 times in a row...

**Comment by TheBottomFragger** [comment]
Have you checked if forced cool-down is on when this happens? When this happened to me the last times I did it, it was because forced cooldown got turned on in the middle of the mission

**Comment by TdotG** [comment]
Nah, it was on none all the times I did it.

**Comment by fkk-cz** [comment]
> Have you checked if forced cool-down is on when this happens? When this happened to me the last times I did it, it was because forced cooldown got turned on in the middle of the mission

Not sure where this is coming from or why it's being speculated on, I've already mentioned in https://github.com/fkk-cz/noire-public/issues/836#issuecomment-1126658522 forced cooldown has nothing to do with mission payout.

Probably need to add some logging to figure out which validity check is failing to prevent payout.

**Comment by cxerq** [comment]
> > Have you checked if forced cool-down is on when this happens? When this happened to me the last times I did it, it was because forced cooldown got turned on in the middle of the mission
> 
> Not sure where this is coming from or why it's being speculated on, I've already mentioned in [#836 (comment)](https://github.com/fkk-cz/noire-public/issues/836#issuecomment-1126658522) forced cooldown has nothing to do with mission payout.
> 
> Probably need to add some logging to figure out which validity check is failing to prevent payout.

I think the issue could be related to multiple people getting the same mission!

**Comment by TdotG** [comment]
That’s also a possibility. On one of them, there was another person who had the same one and they let me take it. But when I got to the drop off it said, “park the vehicle”, which I did and nothing happened. The next few all did the same thing and k never got my money for it.

**Comment by ItsGabble** [comment]
> > Have you checked if forced cool-down is on when this happens? When this happened to me the last times I did it, it was because forced cooldown got turned on in the middle of the mission
> 
> Not sure where this is coming from or why it's being speculated on, I've already mentioned in [#836 (comment)](https://github.com/fkk-cz/noire-public/issues/836#issuecomment-1126658522) forced cooldown has nothing to do with mission payout.
> 
> Probably need to add some logging to figure out which validity check is failing to prevent payout.

I just tried one when I assumed cooldown would be thrown on shortly after starting and the payout was scuffed. It definitely could just be weird timing/confirmation bias. I got a clip of the mission and payout not working for reference if needed.

**Comment by fkk-cz** [comment]
Added verbose logging to determine which validity check is failing. https://github.com/fkk-cz/noire/commit/4fb218470eaeb283d86936ff2d32661c4f606574

**Comment by fkk-cz** [comment]
The error checking indicates these payouts are failing due to incorrectly selected mission data, most likely caused by players starting a new mission shortly after completing or failing a previous one. In both cases, the data still exists in the mission table as the timeout (approx. 20-30 mins?) has not yet expired. As a result, the incorrect key-value pair is selected and the validity checks will obviously fail.

Can be solved by tracking mission completed and failed state, and excluding both types when searching the mission table.

**Comment by fkk-cz** [comment]
Looks like most of the issues related to invalid mission source have been fixed. Other smaller issues I've noticed are most likely caused by players exiting the vehicle manually -- instead of waiting for the server to do it automatically -- and an erroneous `break` statement in the `entityRemoved` handler. Both of these are fixed as well.
