### ISSUE TITLE
Cant store trailers again

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire-public#877]
Something happened with recent changes that you can't store trailers again

Third eye will not prompt

**Comment by Stagonium** [comment]
I was able to get in and store my trailer by hitting F to sit inside like before.

**Comment by fkk-cz** [comment]
Targeting system was updated. 

> I was able to get in and store my trailer by hitting F to sit inside like before.

No idea how that is even possible when there have been no changes to any trailer-related metas.

**Comment by MinoritySanta** [comment]
This was still an issue yesterday.. Not sure about goosenecks, but we could not store small trailers.. no prompt to climb in

FYI for those struggling with this.  Leave your trailers at the bottom of the pit in the mines or parking lot at sell mines.  Much less of a chance it despawns.  I left mine there for 5 hours yesterday after flying in and out and it was still there.  Just park them proper!!

**Comment by RichieRockefeller** [comment]
This is true. I was doing a deal with an individual today and he was selling a whole small rig to me as a package and he could not get in. He tried pressing F from multiple spots, unlocking it, and using his third eye (left alt). The only way people have been able to do it is by taking it out of the garage and while sitting in it when it comes it, then putting it up for sale. The issue today was that the guy I was buying it from had stored it last at a garage in the city and he is a bronze supporter so that method would not work if we tried it.

**Comment by norwegianoak** [comment]
sometimes I experience that the trailer even starts to fly and act cursed, its living its own life flying around. Cant enter it with alt either.

**Comment by No-Yes1** [comment]
So, i've just tested this out, there is no Left ALT option to enter the vehicle for a ``trailercar``, and you are unable to enter the vehicle, to store it in a garage. You can enter the gooseneck trailer by pressing F

**Comment by RichieRockefeller** [comment]
Goosenecks seem to be fine with pressing F as of now. Small trailers still can't be stored or entered at all.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/noire_vehicles/commit/a85dc8a3a8401f1bc616d29480dfd0ef5749ec5e.

**Comment by MinoritySanta** [comment]
Small trailers still not working/cannot store
