### ISSUE TITLE
Hunting: suggested improvements

### ISSUE THREAD

**Issue by MinoritySanta** [fkk-cz/noire-public#890]
Tried Hunting with some friends for the last 2 nights and it's actually a lot of fun.

A few things we've noticed that don't seem right.

1) cougars spawn at an incredibly high rate.  I get that's a hazard you would have to deal with hunting, but it seems like these things are spawning every 10 minutes.  That seems excessive, but maybe that's intended to be that way? I feel like 1 or 2 cougars per hunting session should be the "limit" (based on 3 or 4 hour sessions) 

2) Tumble damage leading to death.  If your player stumbles up a steep hill, he will roll down the hill and die. You can't recover and you're just rolling down grass (not rocks).  Not sure if this can be adjusted, but I'm not sure tumbling down a grass hill should lead to death.  For reference, one of the times this happened, I drove up the hill in a vehicle, parked the vehicle and then go out.  My player basically fell out of the vehicle and rolled into his death and the vehicle obviously stayed put

**Comment by Stagonium** [comment]
> cougars spawn at an incredibly high rate.

I have noticed that the cougars spawn in the same spot every time, and am just wary whenever I go that way. 

> Tumble damage leading to death.

This is certainly a problem up in the hilly areas, but i do think the stumbling damage is a vanilla GTA thing, and I am unsure if it would be changed in here. What I started to do instead of worrying about that was bringing a bike up with me to ride up and down the hills, lowering the chances of falling, granted if I do fall it probably hurts a lot more.

**Comment by MinoritySanta** [comment]
There was a group of 5 of us and we were all in different areas of the hunting zone, and the cougars spawned everywhere for each of us.. So I'm not sure they spawn in a specific zone more-so than they do spawning in areas of a player

I brought a Gladiator Rubicon up, and I parked it, got out of the car and tumbled to my death

**Comment by fkk-cz** [comment]
Both of your 'suggested improvements' can be avoided by changing player behavior (being more alert and careful when exiting a vehicle?) and are intended to be part of the job.
