### ISSUE TITLE
Coke Gathering Location or Interior

### ISSUE THREAD

**Issue by Arvecci** [fkk-cz/noire-public#938]
Im just going to make this short and simple. I believe the price of Meth should be raised to be atleast equal or more than a package of weed. Currently you can find packaged weed easily by running the yacht, or you can grind it out in the fields. With meth, it requires you to drive all the way out to county, get the chemicals, grab empty cans, and then cook it all down, twice. Theres alot of work to put into it for it to only be worth 300/pack. There is almost no incentive to actually grinding meth out, and this makes it a very poor player in the drug scene. Aside from that, we also need a place to actually grind cocaine out. be it picking leaves, taking them, to a place for processing, and then to the current building for production. I guess the last thing I can add is an offline sell option, but the drugs will sell for remarkably less when no cops are around. With as grindy as they are, I dont see a reason somebody would sell their whole inventory for half the price. But, it would be a good idea for those that aren't able to be in city when there are no cops.

**Comment by fkk-cz** [comment]
Meth price is low because of people who still have large stashes from when there was an unintended mass gathering bug. Until these packs are mostly sold, the price will not be raised to match the extra effort and time required to gather and produce meth.

> Aside from that, we also need a place to actually grind cocaine out. be it picking leaves, taking them, to a place for processing, and then to the current building for production.

Probably not a bad idea, provided a suitable open interior in a good location can be found.

> I guess the last thing I can add is an offline sell option, but the drugs will sell for remarkably less when no cops are around.

Why do people *keep* suggesting drug sales with no police online? **This is not happening, and will never happen**. There are multiple ways to make dirty money (see: petty theft, auto theft missions, etc.) and police have pretty good coverage (almost 12-16 hours of the day), even with all the shootouts and whining that people have been engaged in recently.

**Comment by AustinM0527** [comment]
To further add on to this, an idea with picking weed. Considering we pick a plant and only get 1 untrimmed, which takes 15 sec per. A thought to possibly “balance” weed is to give a chance of getting more than 1 per plant, like a chance of getting 1-3. Or if having the chance to get more per plant is “too much” maybe decrease the time of picking. Just throwing the thought out there, more than welcome to add.

**Comment by fkk-cz** [comment]
Added in https://github.com/fkk-cz/noire/commit/c09770e13a2db91ade137b8d687e0467dc907cc4.

Weed & meth still need to be adjusted/changed.

**Comment by Stagonium** [comment]
Someone correct me if I am wrong, but every time I have tried to go to the new coke gathering location, it says it is out of raw materials. Not sure if I am just missing the window when it refills repeatedly, as it has been 5/6 times now, or if it is currently not refilling like it used to do back in the previous locations in Paleto, Lumber Yard, and the Airport warehouse.

**Comment by Mynameisnotlenny** [comment]
> Someone correct me if I am wrong, but every time I have tried to go to the new coke gathering location, it says it is out of raw materials. Not sure if I am just missing the window when it refills repeatedly, as it has been 5/6 times now, or if it is currently not refilling like it used to do back in the previous locations in Paleto, Lumber Yard, and the Airport warehouse.

Believe it is broken have only been able to gather from it once and that was the first day it was implemented and it was right after tsunami, have tried repeatedly over the last few days with the same results.

**Comment by Krazij** [comment]
I believe the materials refill every day after restart. So I’ve  a heard  of  people waking up at 5am PST right after restart who have no life .  And just drain all the materials before people can actually even wake up and have their coffee. This definitely needs to be addressed because it’s not fair to people who are one different time zones either. Shouldn’t have to forces to wake that early just to go fight for a fee coke packs. I get that’s its limited due to it being close to people homes . But it’s needs to be refilled every few hours for everyone’s fair chance at it.

**Comment by Krazij** [comment]
Yea maybe

**Comment by fkk-cz** [comment]
https://github.com/fkk-cz/noire/commit/f33ae1334ced045b45660f7efd4ef915002fbe16 fixes this issue.
