### ISSUE TITLE
Push to talk not working while using left alt

### ISSUE THREAD

**Issue by Stagonium** [fkk-cz/noire-public#947]
I noticed this while mirandizing and preparing to search suspects while on duty, but you cant use push to talk while you are holding the left alt interaction key. I imagine this could be an issue for criminals frisking people as well and should probably be fixed.

**Comment by fkk-cz** [comment]
Fixed in https://github.com/fkk-cz/qtarget/commit/1829bdf38350f6ba96d79ca828b6d03ef5d0a227. Also disabled targeting if dead (apparently people were abusing this too) and removed the unaesthetic outline drawing on vehicle entities https://github.com/fkk-cz/qtarget/commit/13d1e02b0c6f45afe6bf79246d7830440642fb79.
