### ISSUE TITLE
Auto Theft Missions

### ISSUE THREAD

**Issue by xFooliee** [fkk-cz/noire-public#973]
While I totally get stealing other's vehicles makes sense, is there anyway that we can get certain areas to be blocked off from getting stolen? Such as the selling mine spot, mine spot, and LSPD. Seems kind of shitty to steal someone's truck while they are working doing Legals and basically can still take stuff out the back of their truck if someone is cold enough to do so and LSPD wise, just makes no sense to have to get a vehicle that is stuck inside LSPD as we will never be able to reach it or get in, without someone letting us through the gate which is very unlikely.

**Comment by CasperBoiRL** [comment]
where are these missions at?

**Comment by xFooliee** [comment]
> where are these missions at?

I'm referencing to the missions that choose the spots such as selling mines, LSPD (in town) and the mining spot (county).

**Comment by fkk-cz** [comment]
There is no current way to check whether a set of coords are in a safezone server-side, as the safezone script is client-only. Regardless, I don't see how this is _that_ much of an issue to the point where players can't simply deal with it instead of complaining at the slightest amount of inconvenience (e.g. getting your vehicle stolen while running an autoclicker at mining)?
